sudo: false
language: cpp

matrix:
  include:
    # works on 
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++5"
        - CXX_FLAGS=-std=c++11
before_install:
    - eval "${MATRIX_EVAL}"

script:
  - mkdir build
  - cmake ..
  - make
  - make test